### ISSUE TITLE
Dex version 040 is not supported

### ISSUE THREAD

**Issue by toraidl** [REAndroid/APKEditor#100]
Hi,

Exception in thread "main" org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 040 is not supported
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:97)
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:73)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.fromInputStream(DexBackedDexFile.java:144)
	at org.jf.dexlib2.DexFileFactory.loadDexContainer(DexFileFactory.java:248)
	at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:153)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:162)
	at org.jf.baksmali.Main.main(Main.java:102)

**To Reproduce**
1. Used version '1.3.7
2. Operating system 'Linux bruce-ubuntu 6.6.0-14-generic
3. Command 'java -jar ~/Downloads/APKEditor-1.3.7.jar d -f -i tmp/miui-services.jar -o tmp/miui-services'

**Used apk file**
[miui-services.zip](https://github.com/REAndroid/APKEditor/files/14976949/miui-services.zip)

**Comment by toraidl** [comment]
Hi , 
I have tired the latest apk built in Actions, it works.
Thanks.
