### ISSUE TITLE
File dont work after merge

### ISSUE THREAD

**Issue by ufrmaster** [REAndroid/APKEditor#14]
sometimes games dont work after merge. For example - https://apkcombo.com/ru/crazy-gun-inventor/com.twoski.CrazyGunInventor/

I downloaded this game, unzip + merge + sign, but after open its just crashing.

**Comment by REAndroid** [comment]
Check your log cat, not related to merging process. You need to do some mod on your dex code

```console
E AndroidRuntime: Process: com.rsgapps.idle.expansion.tycoon, PID: 10353
E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.pairip.application.Application: com.pairip.SignatureCheck$SignatureTamperedException: Apk signature is invalid.
E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1136)
E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6216)
E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:238)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E AndroidRuntime: Caused by: com.pairip.SignatureCheck$SignatureTamperedException: Apk signature is invalid.
E AndroidRuntime: 	at com.pairip.SignatureCheck.verifyIntegrity(SignatureCheck.java:57)
E AndroidRuntime: 	at com.pairip.application.Application.attachBaseContext(Unknown Source:0)
E AndroidRuntime: 	at android.app.Application.attach(Application.java:237)
E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)

```

**Comment by REAndroid** [comment]
No response and I am closing this issue
