### ISSUE TITLE
The merged apk file is an invalid file.

### ISSUE THREAD

**Issue by lovely3x** [REAndroid/APKEditor#34]
I downloaded an apk file named GPark_1.3.0_apkcombo.com.xapk from apkcombo.com, and then used the following command to merge it into an apk file:
`java -jar APKEditor-1.2.1.jar m -i GPark_1.3.0_apkcombo.com.xapk`

The command executed successfully and generated an output file named GPark_1.3.0_apkcombo.com_merged.apk.
However, I cannot install it on my device, and I'm unable to open it using jadx as well. Jadx gives the following error message:

```
Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
	at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1537)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:97)
	... 8 common frames omitted
```
[Here is the attachment link for the APK](https://drive.google.com/file/d/1LQRfxIqLsQliXlwpWktGAiSsnhjUpyV9/view?usp=sharing), Do you have any suggestions?

**Comment by REAndroid** [comment]
I can not reproduce your issue, I merged your XAPK and installs fine.
I guess your signer tool messed zip structure. 
- Try sign with apksigner that comes with android sdk ( located $ANDROID_HOME/build-tools/x.x.x/ )
- What is your OS platform ( mac/linux ...) ?

**Comment by lovely3x** [comment]
Thanks for your reply, and I am using the Windows 10.

It's very strange that it works fine when I run it from the source code using IDEA. However, it doesn't work properly when I run it from the JAR file downloaded from GitHub or the JAR file built from the source code using Fat JAR.

Initially, I thought it might be due to differences in JDK versions. However, I have checked and confirmed that I am using JDK 11 in both scenarios.

In the end, I tried executing the command with JDK version 11 on Ubuntu, and it worked fine. I believe this might be related to the default encoding of the os or specific system configurations.

**Comment by REAndroid** [comment]
I think your windows os default character encoding is different. I enforced all headers to use UTF-8 encoding.
Please use this [APKEditor-1.2.1-test.zip](https://github.com/REAndroid/APKEditor/files/11666843/APKEditor-1.2.1-test.zip) and let me know your results

**Comment by lovely3x** [comment]
Thanks again.
I think you are right. I tested the jar file you provided, and it works fine.

**Comment by REAndroid** [comment]
Thanks for testing, I will fix it on next release
