### ISSUE TITLE
The latest version 1.2.2 fails to compile back with json

### ISSUE THREAD

**Issue by sekaiacg** [REAndroid/APKEditor#36]
**wrong information:**
```
java -jar APKEditor.jar b -i Home_decompile_json

00.000 I: [BUILD] Building ...
   Input: Home_decompile_json
 Output: Home_decompile_json_out.apk
 ---------------------------- 
00.022 I: [BUILD] Scanning JSON directory ...
00.025 I: [BUILD] Scanning: Home_decompile_json
00.061 I: [BUILD] Building dex ...
00.062 [BUILD] classes2.dex
00.063 I: [BUILD] Scanning root directory ...
00.071 I: [BUILD] Restoring original file paths ...

Unexpected error:
java.io.IOException: No package sub directory found in : Home_decompile_json/resources
java.lang.IllegalArgumentException: java.io.IOException: No package sub directory found in : Home_decompile_json/resources
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:754)
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:789)
	at com.reandroid.apk.ApkModule.listResFiles(ApkModule.java:560)
	at com.reandroid.apk.ApkModule.listResFiles(ApkModule.java:556)
	at com.reandroid.apk.PathMap.restore(PathMap.java:37)
	at com.reandroid.apk.ApkModuleEncoder.restorePathMap(ApkModuleEncoder.java:95)
	at com.reandroid.apk.ApkModuleEncoder.scanDirectory(ApkModuleEncoder.java:42)
	at com.reandroid.apkeditor.compile.Builder.buildJson(Builder.java:65)
	at com.reandroid.apkeditor.compile.Builder.run(Builder.java:45)
	at com.reandroid.apkeditor.compile.Builder.execute(Builder.java:152)
	at com.reandroid.apkeditor.Main.execute(Main.java:68)
	at com.reandroid.apkeditor.Main.main(Main.java:41)
Caused by: java.io.IOException: No package sub directory found in : Home_decompile_json/resources
	at com.reandroid.apk.TableBlockJsonBuilder.scanDirectory(TableBlockJsonBuilder.java:41)
	at com.reandroid.apk.SplitJsonTableInputSource.getTableBlock(SplitJsonTableInputSource.java:56)
	at com.reandroid.apk.ApkModule.loadTableBlock(ApkModule.java:866)
	at com.reandroid.apk.ApkModule.getTableBlock(ApkModule.java:748)
	... 11 more
```

apk file: [Home_test1.zip](https://drive.google.com/file/d/1MJHG-fkSXvMTe9b5o47NQ4m0P9v_t5X6/view?usp=sharing)

**Comment by REAndroid** [comment]
Thanks for reporting, I updated jar  [APKEditor-1.2.2.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.2/APKEditor-1.2.2.jar) 

BTW: _What is your opinion on the new directory structure and naming_ ?

**Comment by sekaiacg** [comment]
> Thanks for reporting, I updated jar [APKEditor-1.2.2.jar](https://github.com/REAndroid/APKEditor/releases/download/V1.2.2/APKEditor-1.2.2.jar)
> 
> BTW: _What is your opinion on the new directory structure and naming_ ?

After testing, the problem has been solved.

The current directory structure is clearer and easier to modify.
I agree with this idea.
