### ISSUE TITLE
Bug on android 13

### ISSUE THREAD

**Issue by abodinagdat16** [REAndroid/APKEditor#52]
i get the bug below 👇 when i use that command
**To Reproduce**
1. Used version 'last version'
2. Operating system 'android'
3. Command 'p -i /storage/emulated/0/NewProject2.apk'

01:55.335 I: [PROTECT] Protecting ...
   Input: /storage/emulated/0/NewProject2.apk
 Output: /storage/emulated/0/NewProject2_protected.apk
 ---------------------------- 
01:55.335 I: [PROTECT] Loading apk ...
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.my.newproject13.CmdTask.run(CmdTask.java:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: com.reandroid.archive.io.ArchiveFileEntrySource
	at com.reandroid.archive.ArchiveFile.createInputSource(ArchiveFile.java:36)
	at com.reandroid.archive.Archive.mapEntrySource(Archive.java:95)
	at com.reandroid.archive.Archive.createZipEntryMap(Archive.java:52)
	at com.reandroid.apk.ApkModule.loadApkFile(ApkModule.java:1095)
	at com.reandroid.apkeditor.protect.Protector.run(Protector.java:48)
	at com.reandroid.apkeditor.protect.Protector.execute(Protector.java:158)
	at com.reandroid.apkeditor.Main.execute(Main.java:80)
	at com.reandroid.apkeditor.Main.main(Main.java:41)
	... 3 more
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.reandroid.archive.InputSource.<clinit>(InputSource.java:270)
	at com.reandroid.archive.ArchiveFile.createInputSource(ArchiveFile.java:36)
	at com.reandroid.archive.Archive.mapEntrySource(Archive.java:95)
	at com.reandroid.archive.Archive.createZipEntryMap(Archive.java:52)
	at com.reandroid.apk.ApkModule.loadApkFile(ApkModule.java:1095)
	at com.reandroid.apkeditor.decompile.Decompiler.run(Decompiler.java:39)
	at com.reandroid.apkeditor.decompile.Decompiler.execute(Decompiler.java:127)
	at com.reandroid.apkeditor.Main.execute(Main.java:64)
	... 4 more

**Comment by REAndroid** [comment]
Your build is incorrect ! Clone again

**Comment by abodinagdat16** [comment]
> Your build is incorrect ! Clone again

i used this version....from this repo https://github.com/REAndroid/APKEditor/releases/download/V1.2.7/APKEditor-1.2.7.jar

**Comment by REAndroid** [comment]
I didn't test it on android os, did you make your app or how you run the jar ?

**Comment by abodinagdat16** [comment]
i make a new app for apk editing.... i use this code to execute:Method main = clazz.getMethod("main", String[].class);
   main.invoke(null, (Object)args);
clazz file is com.reandroid.apkeditor.Main
and args is commands

**Comment by REAndroid** [comment]
This might be related to java 8 compatibility (google search/clear build cache completely), decompile your own "editor-apk" and see if `Lcom/reandroid/archive/io/ArchiveFileEntrySource;` class exists on smali

**Comment by abodinagdat16** [comment]
i will try....

**Comment by abodinagdat16** [comment]
The class Lcom/reandroid/archive/io/ArchiveFileEntrySource 
is exists in apk file ....i will try to use jdk 17 ....
